Patch to allow HTML link processing
mogsdad/SheetConverter pull request #19
Opened 2020-07-30 14:53 UTC by ChadEmory

Please import the following patch to enable HTML links to be processed by the Script.

2021-01-14 21:03 UTC, mogsdad commented on SheetConverter/Code.gs
> +        Logger.log("row - " + row + " col - " + col);
Remove `Logger` calls.

2021-01-14 21:04 UTC, mogsdad requested changes

2021-01-14 21:04 UTC, mogsdad commented on SheetConverter/Code.gs
> +        Logger.log("row - " + row + " col - " + col);
Remove `Logger` calls.

2021-01-14 22:29 UTC, ChadEmory commented
Removed all logger references in my version of the code. I also noticed there is more Logger entries in other areas of the code that you might want to clear out as well.

2021-01-18 21:14 UTC, mogsdad commented
> Removed all logger references in my version of the code. I also noticed there is more Logger entries in other areas of the code that you might want to clear out as well.

There is only one instance in code (vs in comment examples), and it serves the specific purpose of reporting back to the user that the format they have provided is not supported. That's a stark difference from leftover debugging code.

2021-01-18 21:14 UTC, merged

2021-01-18 21:14 UTC, mogsdad commented
Thanks for the PR, Chad - merged.